### ISSUE TITLE
problem with streaming videos

### ISSUE THREAD

**Issue by vahabahmadvand** [JannikLassahn/unity-videoplayer-helper#5]
here is the error message
"The byte stream type of the given URL is unsupported"

**Comment by JannikLassahn** [comment]
The error seems to originate from the video player component. Since this component is shipped with Unity, please refer to the Unity Forums for further questions. 
The video player is pretty limited in streaming use cases, so you might have to incorporate other libraries or figure out how to get the video stream in one of the supported formats described [here](https://docs.unity3d.com/Manual/VideoSources-FileCompatibility.html).
