### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by suiboli314** [JannikLassahn/unity-videoplayer-helper#6]
According to [Some of the best optimization tips for Unity UI](https://unity3d.com/how-to/unity-ui-optimization-tips)
> each Layout Group adds one GetComponents call to each child Layout Element’s dirtying process, making nested Layout Groups extremely bad for performance. 
Solution: Avoid Layout Groups wherever possible.

I haven't take a close look at Viemo Example, but for Youtube Example, there are nested layout groups which said should be avoided to improve the performance. (I don't think people intend to dirty their layout by using Layout Group, but the article points it out anyway)

I managed to integrate your Youtube Example into a world space Canvas with all controls working. But it doesn't work after I add another UI Canvas with UI camera. 
Maybe it doesn't seem to be a good idea to call camera.main in Timeline.cs to find the current camera? Or I need to optimal use of Graphic Raycaster in other way?

Please correct me if I am wrong, I am still a noob for unity world.

**Comment by JannikLassahn** [comment]
Performance wasn't a major goal when I wrote this helper library, but your points are valid nonetheless. Also, with the introduction of UIElements in mind I'm hesitant to invest a lot of time into the existing solution ;) 

Maybe you could change the timeline code so that it can access the camera through a public property or some other configurable way. I'm not 100% sure as I wrote all that code 2 years ago.
